// Canonical tag vocabulary for the `tags[]` field shared by all five content
// collections. Unlike `saints.ts`, this is a closed set rather than a
// display-name lookup with a humanize() fallback: tags exist specifically to
// power cross-entry discovery (browse-by-tag, search facets), so a typo or
// one-off synonym ('helena' vs 'st-helena') silently fragments that surface
// instead of erroring. `content.config.ts` validates every entry's tags
// against TAG_SLUGS at build time - adding a tag to content means adding it
// here first.
export const TAG_LABELS = {
  'acheiropoieta': 'Acheiropoieta',
  'all-souls': 'All Souls',
  'animal-blessing': 'Animal Blessing',
  'animal-companion-legend': 'Animal Companion Legend',
  'anthony-of-padua': 'Anthony of Padua',
  'arthurian-legend': 'Arthurian Legend',
  'ash-wednesday': 'Ash Wednesday',
  'bernardine-of-siena': 'Bernardine of Siena',
  'bestiary': 'Bestiary',
  'bilocation': 'Bilocation',
  'catacombs': 'Catacombs',
  'catherine-of-siena': 'Catherine of Siena',
  'children': 'Children',
  'christmas-stocking': 'Christmas Stocking',
  'christogram': 'Christogram',
  'cologne-cathedral': 'Cologne Cathedral',
  'constantine-vision': "Constantine's Vision",
  'crown-of-thorns': 'Crown of Thorns',
  'devotional-art': 'Devotional Art',
  'dragon-legend': 'Dragon Legend',
  'epiphany': 'Epiphany',
  'eucharist': 'Eucharist',
  'exaltation-of-the-cross': 'Exaltation of the Cross',
  'fatima': 'Fatima',
  'fioretti': 'Fioretti',
  'food-tradition': 'Food Tradition',
  'francis-of-assisi': 'Francis of Assisi',
  'french-revolution': 'French Revolution',
  'golden-legend': 'Golden Legend',
  'heraldry': 'Heraldry',
  'holy-grail': 'Holy Grail',
  'holy-house-of-loreto': 'Holy House of Loreto',
  'holy-lance': 'Holy Lance',
  'holy-name': 'Holy Name',
  'holy-rosary': 'Holy Rosary',
  'holy-souls': 'Holy Souls',
  'holy-tunic': 'Holy Tunic',
  'hunters-patron': "Hunters' Patron",
  'ihs': 'IHS',
  'immaculate-heart': 'Immaculate Heart',
  'inedia': 'Inedia',
  'ireland': 'Ireland',
  'jesuits': 'Jesuits',
  'joseph-of-cupertino': 'Joseph of Cupertino',
  'last-supper': 'Last Supper',
  'legend-migration': 'Legend Migration',
  'legend-vs-biology': 'Legend vs. Biology',
  'leo-xiii': 'Leo XIII',
  'lepanto': 'Lepanto',
  'levitation': 'Levitation',
  'liturgical-blessing': 'Liturgical Blessing',
  'liturgical-object': 'Liturgical Object',
  'luminosity': 'Luminosity',
  'mardi-gras': 'Mardi Gras',
  'margaret-mary-alacoque': 'Margaret Mary Alacoque',
  'marian-devotion': 'Marian Devotion',
  'marian-shrine': 'Marian Shrine',
  'may-crowning': 'May Crowning',
  'napoleonic-era': 'Napoleonic Era',
  'nicholas-of-flue': 'Nicholas of Flue',
  'notre-dame': 'Notre-Dame',
  'odor-of-sanctity': 'Odor of Sanctity',
  'our-lady-of-loreto': 'Our Lady of Loreto',
  'our-lady-of-sorrows': 'Our Lady of Sorrows',
  'padre-pio': 'Padre Pio',
  'palm-sunday': 'Palm Sunday',
  'papal-states': 'Papal States',
  'papal-symbol': 'Papal Symbol',
  'passion-relics': 'Passion Relics',
  'patrick-of-ireland': 'Patrick of Ireland',
  'patron-saint-origin': 'Patron Saint Origin',
  'patronage-origin': 'Patronage Origin',
  'penal-laws': 'Penal Laws',
  'persecution': 'Persecution',
  'philip-neri': 'Philip Neri',
  'pilgrimage': 'Pilgrimage',
  'pius-ix': 'Pius IX',
  'pius-vii': 'Pius VII',
  'priest-holes': 'Priest Holes',
  'private-revelation': 'Private Revelation',
  'purgatory': 'Purgatory',
  'recusant-england': 'Recusant England',
  'relics-of-the-magi': 'Relics of the Magi',
  'sacred-heart': 'Sacred Heart',
  'saint-blaise-day': 'Saint Blaise Day',
  'saint-nicholas-day': 'Saint Nicholas Day',
  'santiago-de-compostela': 'Santiago de Compostela',
  'scala-sancta': 'Scala Sancta',
  'seamless-robe': 'Seamless Robe',
  'snake-legend': 'Snake Legend',
  'st-helena': 'St. Helena',
  'st-joseph': 'St. Joseph',
  'stag-vision': 'Stag Vision',
  'symbol-origin': 'Symbol Origin',
  'teresa-of-avila': 'Teresa of Avila',
  'true-cross': 'True Cross',
  'veil-of-veronica': 'Veil of Veronica',
  'wolf-legend': 'Wolf Legend',
  'world-war-ii': 'World War II',
} as const;

export type TagSlug = keyof typeof TAG_LABELS;

// Non-empty tuple form z.enum() requires.
export const TAG_SLUGS = Object.keys(TAG_LABELS) as [TagSlug, ...TagSlug[]];

export function tagLabel(slug: string): string {
  return TAG_LABELS[slug as TagSlug] ?? slug;
}
